---

#poogladaj jeszcze
#https://github.com/AlbanAndrieu/ansible-awstats/blob/master/tasks/awstats.yml

#test updates with
#/usr/lib/cgi-bin/awstats.pl -config=dobrekuchnie.com -update

#tested on: Ubuntu 18.04 (bionic)


- name: install awstats package
  package: #os independent
    name: awstats
    state: present

- name: install perl dependencies
  package:
    name: libgeo-ipfree-perl
    state: present


#script needed to run perl through cgi on nginx
#more info about it
#https://wiki.archlinux.org/index.php/Awstats
#https://kamisama.me/2013/03/20/install-configure-and-protect-awstats-for-multiple-nginx-vhost-on-debian/
- name: copy cgi-bin.php file
  copy:
    src: files/etc/nginx/cgi-bin.php
    dest: /etc/nginx/
    owner: www-data
    group: www-data

- name: set awstats.pl file owner (for better security)
  file:
    path: /usr/lib/cgi-bin/awstats.pl
    owner: www-data
    group: www-data



- name: configure nginx with awstats.conf
  copy:
    src: etc/nginx/sites-available/awstats.conf
    dest: /etc/nginx/sites-available

- name: nginx - make this configuration enabled 
  file:
    src: ../sites-available/awstats.conf
    dest: /etc/nginx/sites-enabled/awstats.conf
    state: link


# configure monitoring

- name: create awstats config file for {{ monitored_domain }} (SkipHosts {{ skip_hosts }}
  copy:
    remote_src: yes
    force: no           #don't copy if already copied
    src: /etc/awstats/awstats.conf
    dest: /etc/awstats/awstats.{{ monitored_domain }}.conf



- name: configure awstats for awstats.{{ monitored_domain }}.conf, set SkipHosts ({{ access_log_name }})
  lineinfile:
    path: /etc/awstats/awstats.{{ monitored_domain }}.conf
    regexp: '^SkipHosts='
    line: 'SkipHosts="{{ skip_hosts }}"'


- name: configure awstats for awstats.{{ monitored_domain }}.conf, set access.log name ({{ access_log_name }})
  lineinfile:
    path: /etc/awstats/awstats.{{ monitored_domain }}.conf
    regexp: '^LogFile='
    line: 'LogFile="/var/log/nginx/{{ access_log_name }}"'


- name: configure awstats for awstats.{{ monitored_domain }}.conf, set LogFormat ({{ access_log_name }})
  lineinfile:
    path: /etc/awstats/awstats.{{ monitored_domain }}.conf
    regexp: '^LogFormat='
    line: 'LogFormat=1'


- name: configure awstats for awstats.{{ monitored_domain }}.conf, set SiteDomain ({{ access_log_name }})
  lineinfile:
    path: /etc/awstats/awstats.{{ monitored_domain }}.conf
    regexp: '^SiteDomain='
    line: 'SiteDomain="{{ monitored_domain }}"'


- name: configure awstats for awstats.{{ monitored_domain }}.conf, set HostAliases ({{ access_log_name }})
  lineinfile:
    path: /etc/awstats/awstats.{{ monitored_domain }}.conf
    regexp: '^HostAliases='
    line: 'HostAliases="localhost 127.0.0.1 {{ monitored_domain }}"'


- name: configure awstats for awstats.{{ monitored_domain }}.conf, uncomment plugin "tooltips" "graphgooglechartapi" "geoipfree"
  lineinfile:
    path: /etc/awstats/awstats.{{ monitored_domain }}.conf
    regexp: '^LoadPlugin="{{item}}"'
    insertafter: '^#LoadPlugin="{{item}}"'
    line: 'LoadPlugin="{{item}}"'
  with_items:
    - tooltips
    - graphgooglechartapi
    - geoipfree


